name: Python CI

# trigger the workflow on any push tomain branch or pull request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check the code repo:
    - name: Check out code
      uses: actions/checkout@v2

    # step2: Setup python env
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install Dependecies
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    # Step 4: Run Tests
    - name: Run tests
      run: pytest
